#Documentation for an ATUS Api
*"The American Time Use Survey (ATUS) measures the amount of time people spend doing various activities, such as paid work, childcare, volunteering, and socializing." - http://www.bls.gov/tus/*

This API allows easy access to the ATUS data. The individual can search by both the respondent or the activity. 

A respondent query returns the activities, along with the corresponding participation time, in which there was a participation time greater than 0 minutes, as well as some other useful demographic information.

An activity query returns the average participation time per page (explain below) of corresponding respondents.

#####Links to the Data used
* Activity Summary: http://www.bls.gov/tus/datafiles_2014.htm
* Activity Lexicon: http://www.bls.gov/tus/lexiconwex2014.pdf

In [1]:
import requests

### In order to see details on an individual respondent simply call their id number.
```../respondent/<id>/```
###### For Example:

In [2]:
single_respondent = requests.get('https://autus-project.herokuapp.com/respondent/40/')
single_respondent.json()

{'activities': {'010101': 460,
  '010201': 20,
  '020201': 4,
  '020203': 30,
  '020303': 45,
  '020601': 30,
  '020902': 5,
  '110101': 15,
  '120303': 507,
  '120312': 234,
  '160101': 90},
 'age': 66,
 'case_id': 20140101141232,
 'hours_worked_per_week': 40,
 'sex': 2,
 'weight': 1653797.701352}

# *Filtering*

### To filter respondents by attribute, combine one of the filter fields with an operator, and set them some value.

#### Filter Fields
* age
* sex
* hours_worked_per_week
* case_id

####Operators:
* lt
* gt
* lte
* gte

In [3]:
filtered_respondent = requests.get('https://autus-project.herokuapp.com/respondents/?age_lt=20')
filtered_respondent.json()

{'count': 11592,
 'next': 'https://autus-project.herokuapp.com/respondents/?age_lt=20&offset=100',
 'previous': None,
 'results': [{'activities': {'010101': 1145,
    '010201': 60,
    '030101': 30,
    '110101': 30,
    '120303': 30,
    '130116': 90,
    '181101': 10,
    '181301': 45},
   'age': 20,
   'case_id': 20140101140007,
   'hours_worked_per_week': -1,
   'sex': 2,
   'weight': 4891315.82676},
  {'activities': {'010101': 540,
    '010201': 60,
    '020201': 20,
    '020203': 20,
    '050101': 465,
    '110101': 45,
    '120101': 60,
    '120303': 100,
    '120308': 40,
    '180501': 90},
   'age': 16,
   'case_id': 20140101140011,
   'hours_worked_per_week': 35,
   'sex': 2,
   'weight': 23147368.359655},
  {'activities': {'010101': 555,
    '010201': 90,
    '020102': 60,
    '020201': 240,
    '030109': 180,
    '110101': 60,
    '120301': 120,
    '120303': 135},
   'age': 65,
   'case_id': 20140101140028,
   'hours_worked_per_week': -1,
   'sex': 2,
   'weight': 20941823.429044},
  {'activities': {'010101': 780,
    '010201': 60,
    '020201': 10,
    '120301': 350,
    '120303': 110,
    '140101': 110,
    '181401': 20},
   'age': 50,
   'case_id': 20140101140063,
   'hours_worked_per_week': -1,
   'sex': 2,
   'weight': 2505899.417166},
  {'activities': {'010101': 645,
    '010201': 60,
    '020101': 95,
    '020201': 140,
    '020203': 30,
    '020601': 20,
    '020602': 30,
    '030101': 85,
    '030201': 90,
    '050401': 60,
    '110101': 65,
    '120303': 120},
   'age': 23,
   'case_id': 20140101140168,
   'hours_worked_per_week': -1,
   'sex': 2,
   'weight': 15928231.823165},
  {'activities': {'010101': 240,
    '020201': 30,
    '110101': 30,
    '120301': 60,
    '120303': 1080},
   'age': 85,
   'case_id': 20140101140537,
   'hours_worked_per_week': -1,
   'sex': 1,
   'weight': 3622350.817628},
  {'activities': {'010101': 585,
    '010201': 30,
    '050101': 645,
    '070104': 10,
    '110101': 20,
    '120101': 105,
    '180501': 35,
    '180704': 10},
   'age': 27,
   'case_id': 20140101140559,
   'hours_worked_per_week': 72,
   'sex': 1,
   'weight': 3653337.861341},
  {'activities': {'010101': 450,
    '010201': 60,
    '020201': 15,
    '030101': 60,
    '050101': 555,
    '110101': 30,
    '120303': 90,
    '120308': 90,
    '130131': 30,
    '180501': 60},
   'age': 28,
   'case_id': 20140101140610,
   'hours_worked_per_week': 40,
   'sex': 1,
   'weight': 11589604.860274},
  {'activities': {'010101': 425,
    '010201': 70,
    '020201': 154,
    '020902': 12,
    '040402': 30,
    '040501': 5,
    '110101': 30,
    '120101': 231,
    '120303': 276,
    '120312': 75,
    '160101': 8,
    '160102': 5,
    '180209': 15,
    '180405': 4,
    '181201': 30,
    '500106': 70},
   'age': 63,
   'case_id': 20140101140614,
   'hours_worked_per_week': -4,
   'sex': 2,
   'weight': 2019096.316437},
  {'activities': {'010101': 520,
    '010201': 95,
    '020101': 15,
    '020203': 15,
    '020901': 30,
    '020903': 1,
    '110101': 117,
    '120301': 60,
    '120303': 353,
    '120312': 194,
    '130128': 30,
    '181101': 3,
    '181203': 5,
    '181301': 2},
   'age': 85,
   'case_id': 20140101140639,
   'hours_worked_per_week': -1,
   'sex': 1,
   'weight': 5332005.152751},
  {'activities': {'010101': 495,
    '010201': 15,
    '020102': 35,
    '020104': 10,
    '020201': 30,
    '020203': 20,
    '020902': 10,
    '040101': 210,
    '070104': 40,
    '110101': 80,
    '120301': 100,
    '120303': 185,
    '120312': 145,
    '180401': 25,
    '180704': 20,
    '181101': 20},
   'age': 66,
   'case_id': 20140101140665,
   'hours_worked_per_week': 40,
   'sex': 2,
   'weight': 4778595.528829},
  {'activities': {'010101': 670,
    '010301': 5,
    '020201': 15,
    '110101': 35,
    '120303': 445,
    '120308': 90,
    '120312': 60,
    '120404': 60,
    '181204': 60},
   'age': 54,
   'case_id': 20140101140685,
   'hours_worked_per_week': -1,
   'sex': 1,
   'weight': 7015085.157922},
  {'activities': {'010101': 690,
    '020101': 180,
    '020102': 120,
    '020203': 5,
    '030101': 105,
    '030112': 15,
    '070103': 30,
    '120101': 80,
    '120303': 185,
    '180301': 5,
    '180703': 15,
    '181201': 10},
   'age': 31,
   'case_id': 20140101140702,
   'hours_worked_per_week': -1,
   'sex': 2,
   'weight': 6323639.241364},
  {'activities': {'010101': 531,
    '010102': 20,
    '010201': 65,
    '020201': 15,
    '020202': 1,
    '020203': 20,
    '030101': 38,
    '030102': 5,
    '030103': 20,
    '050101': 513,
    '070103': 4,
    '080101': 13,
    '110101': 25,
    '120303': 47,
    '180301': 5,
    '180501': 52,
    '180703': 2,
    '180801': 62,
    '181101': 2},
   'age': 35,
   'case_id': 20140101140725,
   'hours_worked_per_week': 45,
   'sex': 1,
   'weight': 7339555.320589},
  {'activities': {'010101': 510,
    '010201': 20,
    '080401': 30,
    '110101': 150,
    '120301': 520,
    '120303': 190,
    '180804': 20},
   'age': 80,
   'case_id': 20140101140759,
   'hours_worked_per_week': -1,
   'sex': 1,
   'weight': 19564172.363871},
  {'activities': {'010101': 380,
    '010201': 6,
    '020201': 5,
    '020602': 15,
    '020902': 30,
    '050401': 10,
    '070101': 25,
    '120303': 540,
    '160102': 330,
    '180209': 17,
    '180701': 37,
    '500101': 45},
   'age': 37,
   'case_id': 20140101140792,
   'hours_worked_per_week': -1,
   'sex': 1,
   'weight': 17110667.548441},
  {'activities': {'010101': 459,
    '010201': 60,
    '030109': 55,
    '030110': 60,
    '030112': 10,
    '050101': 479,
    '070103': 15,
    '110101': 80,
    '120303': 120,
    '180301': 65,
    '180501': 14,
    '180703': 18,
    '181101': 5},
   'age': 41,
   'case_id': 20140101140804,
   'hours_worked_per_week': 40,
   'sex': 2,
   'weight': 6209017.526033},
  {'activities': {'010101': 535,
    '010201': 105,
    '020201': 120,
    '020203': 45,
    '020601': 5,
    '020901': 120,
    '020902': 90,
    '110101': 105,
    '120303': 120,
    '120304': 60,
    '120312': 75,
    '160101': 60},
   'age': 85,
   'case_id': 20140101140836,
   'hours_worked_per_week': -1,
   'sex': 2,
   'weight': 2068191.833256},
  {'activities': {'010101': 440,
    '010201': 55,
    '020104': 25,
    '020201': 75,
    '070101': 30,
    '110101': 60,
    '120101': 165,
    '120303': 255,
    '120312': 90,
    '130134': 60,
    '160101': 30,
    '160102': 45,
    '180701': 20,
    '181201': 90},
   'age': 67,
   'case_id': 20140101140852,
   'hours_worked_per_week': -1,
   'sex': 1,
   'weight': 2182116.98539},
  {'activities': {'010101': 720, '020904': 2, '110101': 30, '120303': 688},
   'age': 21,
   'case_id': 20140101140854,
   'hours_worked_per_week': -1,
   'sex': 2,
   'weight': 4731635.020056},
  {'activities': {'010101': 478,
    '020101': 30,
    '020102': 2,
    '020201': 30,
    '020203': 30,
    '020602': 30,
    '030106': 30,
    '030109': 90,
    '030201': 60,
    '050101': 646,
    '070103': 10,
    '180703': 4},
   'age': 45,
   'case_id': 20140101140872,
   'hours_worked_per_week': 40,
   'sex': 2,
   'weight': 8369759.181566},
  {'activities': {'010101': 405,
    '010201': 20,
    '020201': 15,
    '020701': 20,
    '050101': 437,
    '070104': 20,
    '110101': 47,
    '120101': 20,
    '120302': 10,
    '120303': 245,
    '120307': 120,
    '180501': 49,
    '180704': 32},
   'age': 62,
   'case_id': 20140101140875,
   'hours_worked_per_week': 50,
   'sex': 1,
   'weight': 11463166.416109},
  {'activities': {'010101': 590,
    '010201': 105,
    '020104': 30,
    '020201': 15,
    '070101': 90,
    '110101': 90,
    '120303': 265,
    '140101': 130,
    '160102': 60,
    '180701': 20,
    '181101': 25,
    '181401': 20},
   'age': 67,
   'case_id': 20140101140876,
   'hours_worked_per_week': 20,
   'sex': 2,
   'weight': 4376665.609382},
  {'activities': {'010101': 480,
    '010201': 30,
    '020101': 2,
    '020102': 10,
    '020201': 70,
    '020203': 40,
    '020902': 178,
    '040501': 30,
    '040507': 10,
    '070101': 120,
    '070104': 94,
    '110101': 45,
    '120303': 265,
    '120312': 15,
    '180405': 23,
    '180701': 8,
    '180704': 20},
   'age': 80,
   'case_id': 20140101140885,
   'hours_worked_per_week': -1,
   'sex': 2,
   'weight': 4659170.172209},
  {'activities': {'010101': 690,
    '010201': 90,
    '020902': 5,
    '080501': 120,
    '110101': 180,
    '120303': 315,
    '180805': 15,
    '181101': 25},
   'age': 61,
   'case_id': 20140101140911,
   'hours_worked_per_week': -1,
   'sex': 2,
   'weight': 10415633.647422},
  {'activities': {'010101': 630,
    '020201': 10,
    '070101': 60,
    '110101': 30,
    '120301': 90,
    '120303': 575,
    '180701': 15,
    '181203': 30},
   'age': 49,
   'case_id': 20140101140940,
   'hours_worked_per_week': -1,
   'sex': 1,
   'weight': 3624692.126833},
  {'activities': {'010101': 420,
    '010201': 55,
    '020201': 40,
    '020902': 45,
    '030101': 155,
    '030103': 95,
    '030112': 20,
    '050101': 444,
    '110101': 90,
    '120303': 10,
    '180301': 50,
    '180501': 13,
    '181101': 3},
   'age': 26,
   'case_id': 20140101140958,
   'hours_worked_per_week': 40,
   'sex': 2,
   'weight': 9199818.278835},
  {'activities': {'010101': 510,
    '010201': 45,
    '020101': 222,
    '020201': 40,
    '020303': 3,
    '020601': 210,
    '110101': 65,
    '120301': 60,
    '120303': 105,
    '120312': 150,
    '160108': 30},
   'age': 66,
   'case_id': 20140101140967,
   'hours_worked_per_week': -1,
   'sex': 2,
   'weight': 3840512.602825},
  {'activities': {'010101': 518,
    '010201': 40,
    '020501': 120,
    '070102': 12,
    '110101': 90,
    '120101': 25,
    '120301': 300,
    '120303': 20,
    '130134': 120,
    '140101': 120,
    '180702': 15,
    '181201': 15,
    '181301': 30,
    '181401': 15},
   'age': 62,
   'case_id': 20140101140973,
   'hours_worked_per_week': 40,
   'sex': 1,
   'weight': 12684691.638659},
  {'activities': {'010101': 640,
    '020201': 50,
    '020402': 60,
    '020501': 30,
    '020601': 60,
    '110101': 10,
    '120101': 120,
    '120303': 437,
    '120312': 30,
    '181201': 3},
   'age': 61,
   'case_id': 20140101140990,
   'hours_worked_per_week': -1,
   'sex': 1,
   'weight': 5305349.062981},
  {'activities': {'010101': 496,
    '010201': 25,
    '020102': 60,
    '020201': 60,
    '020601': 15,
    '040507': 9,
    '070103': 5,
    '110101': 95,
    '120101': 165,
    '120303': 300,
    '120312': 30,
    '180405': 105,
    '180703': 15,
    '181101': 30,
    '189999': 20,
    '500103': 10},
   'age': 47,
   'case_id': 20140101140995,
   'hours_worked_per_week': 45,
   'sex': 1,
   'weight': 7324591.300421},
  {'activities': {'010101': 600,
    '010201': 75,
    '020701': 5,
    '040112': 1,
    '110101': 130,
    '120303': 252,
    '120305': 30,
    '120312': 90,
    '130125': 120,
    '130199': 90,
    '180207': 10,
    '180401': 17,
    '189999': 10,
    '500101': 10},
   'age': 16,
   'case_id': 20140101141014,
   'hours_worked_per_week': -1,
   'sex': 2,
   'weight': 13458916.013599},
  {'activities': {'010101': 510,
    '010102': 60,
    '010201': 120,
    '110101': 20,
    '120303': 730},
   'age': 74,
   'case_id': 20140101141056,
   'hours_worked_per_week': -1,
   'sex': 2,
   'weight': 5276676.909225},
  {'activities': {'010101': 600,
    '010301': 300,
    '020104': 10,
    '020201': 30,
    '070101': 30,
    '110101': 130,
    '120312': 320,
    '180701': 20},
   'age': 70,
   'case_id': 20140101141081,
   'hours_worked_per_week': -1,
   'sex': 1,
   'weight': 2215172.328431},
  {'activities': {'010101': 690,
    '010201': 5,
    '040103': 540,
    '110101': 105,
    '120301': 10,
    '120303': 90},
   'age': 64,
   'case_id': 20140101141134,
   'hours_worked_per_week': -1,
   'sex': 1,
   'weight': 11490070.012269},
  {'activities': {'010101': 445,
    '010201': 95,
    '020203': 20,
    '020901': 5,
    '050101': 460,
    '070104': 10,
    '110101': 85,
    '120301': 30,
    '120303': 158,
    '120312': 60,
    '180209': 7,
    '180501': 35,
    '180704': 30},
   'age': 69,
   'case_id': 20140101141177,
   'hours_worked_per_week': 45,
   'sex': 1,
   'weight': 3347308.753242},
  {'activities': {'010101': 420,
    '010201': 40,
    '020201': 60,
    '030402': 30,
    '110101': 30,
    '120303': 120,
    '120313': 540,
    '130199': 150,
    '500101': 50},
   'age': 56,
   'case_id': 20140101141179,
   'hours_worked_per_week': -1,
   'sex': 2,
   'weight': 12692828.598496},
  {'activities': {'010101': 395,
    '010102': 45,
    '010201': 90,
    '020102': 20,
    '020201': 35,
    '020203': 15,
    '020601': 12,
    '050101': 450,
    '110101': 145,
    '120303': 120,
    '160101': 30,
    '160102': 15,
    '180501': 38,
    '181101': 30},
   'age': 28,
   'case_id': 20140101141180,
   'hours_worked_per_week': 38,
   'sex': 2,
   'weight': 7230358.288219},
  {'activities': {'010101': 540,
    '010201': 30,
    '020201': 15,
    '050101': 240,
    '080501': 30,
    '110101': 60,
    '120303': 150,
    '120312': 85,
    '150101': 60,
    '160108': 60,
    '160199': 60,
    '180501': 50,
    '180805': 60},
   'age': 55,
   'case_id': 20140101141214,
   'hours_worked_per_week': 10,
   'sex': 2,
   'weight': 4911809.207808},
  {'activities': {'010101': 460,
    '010201': 20,
    '020201': 4,
    '020203': 30,
    '020303': 45,
    '020601': 30,
    '020902': 5,
    '110101': 15,
    '120303': 507,
    '120312': 234,
    '160101': 90},
   'age': 66,
   'case_id': 20140101141232,
   'hours_worked_per_week': 40,
   'sex': 2,
   'weight': 1653797.701352},
  {'activities': {'010101': 330,
    '010201': 30,
    '020101': 45,
    '020102': 60,
    '020201': 60,
    '020203': 45,
    '110101': 30,
    '120303': 840},
   'age': 72,
   'case_id': 20140101141282,
   'hours_worked_per_week': -1,
   'sex': 2,
   'weight': 1760787.363082},
  {'activities': {'010101': 390,
    '010201': 60,
    '040112': 45,
    '050101': 600,
    '110101': 45,
    '120303': 30,
    '130203': 150,
    '180401': 75,
    '180501': 30,
    '181302': 15},
   'age': 54,
   'case_id': 20140101141288,
   'hours_worked_per_week': 40,
   'sex': 1,
   'weight': 4169289.689615},
  {'activities': {'010101': 450,
    '010201': 95,
    '020201': 30,
    '040109': 270,
    '070103': 55,
    '110101': 5,
    '120301': 210,
    '140101': 195,
    '180202': 5,
    '180703': 120,
    '181401': 5},
   'age': 66,
   'case_id': 20140101141321,
   'hours_worked_per_week': 35,
   'sex': 1,
   'weight': 5855506.530854},
  {'activities': {'010101': 500,
    '010201': 70,
    '010301': 5,
    '020102': 90,
    '020201': 75,
    '020701': 60,
    '020902': 60,
    '020903': 5,
    '110101': 150,
    '120303': 275,
    '120312': 75,
    '160199': 15,
    '500107': 60},
   'age': 80,
   'case_id': 20140101141331,
   'hours_worked_per_week': -1,
   'sex': 1,
   'weight': 6679171.962004},
  {'activities': {'010101': 515,
    '010201': 35,
    '020201': 30,
    '020303': 60,
    '110101': 170,
    '120303': 630},
   'age': 66,
   'case_id': 20140101141365,
   'hours_worked_per_week': -1,
   'sex': 1,
   'weight': 2904193.631873},
  {'activities': {'010101': 510,
    '010201': 30,
    '020101': 95,
    '020102': 30,
    '020201': 20,
    '020203': 10,
    '030101': 40,
    '030112': 5,
    '110101': 45,
    '120303': 435,
    '130124': 30,
    '140101': 135,
    '180301': 30,
    '181203': 15,
    '181401': 10},
   'age': 36,
   'case_id': 20140101141379,
   'hours_worked_per_week': 40,
   'sex': 1,
   'weight': 1433662.143623},
  {'activities': {'010101': 585,
    '010201': 15,
    '020201': 90,
    '020203': 20,
    '020303': 45,
    '110101': 120,
    '120303': 355,
    '120308': 165,
    '160101': 45},
   'age': 47,
   'case_id': 20140101141381,
   'hours_worked_per_week': 40,
   'sex': 2,
   'weight': 6381051.271597},
  {'activities': {'010101': 360,
    '050101': 820,
    '110101': 120,
    '120301': 20,
    '120303': 120},
   'age': 63,
   'case_id': 20140101141386,
   'hours_worked_per_week': 60,
   'sex': 2,
   'weight': 4384446.284241},
  {'activities': {'010101': 550,
    '010201': 20,
    '050101': 345,
    '110101': 45,
    '120101': 110,
    '120301': 60,
    '120303': 199,
    '160199': 90,
    '180501': 21},
   'age': 18,
   'case_id': 20140101141409,
   'hours_worked_per_week': -4,
   'sex': 2,
   'weight': 9174035.363375},
  {'activities': {'010101': 450,
    '010201': 120,
    '020201': 60,
    '020903': 1,
    '060102': 100,
    '070104': 40,
    '110101': 134,
    '120101': 60,
    '120303': 245,
    '120308': 60,
    '130128': 45,
    '130133': 30,
    '180601': 20,
    '180704': 55,
    '181301': 20},
   'age': 61,
   'case_id': 20140101141418,
   'hours_worked_per_week': -1,
   'sex': 2,
   'weight': 10087906.815736},
  {'activities': {'010101': 870,
    '030405': 60,
    '110101': 60,
    '120303': 60,
    '150101': 240,
    '150102': 120,
    '180304': 10,
    '181101': 20},
   'age': 79,
   'case_id': 20140101141430,
   'hours_worked_per_week': -1,
   'sex': 1,
   'weight': 4274574.627578},
  {'activities': {'010101': 615,
    '010201': 50,
    '050101': 480,
    '060301': 90,
    '110101': 45,
    '120101': 120,
    '120303': 5,
    '120307': 5,
    '180501': 20,
    '181101': 5,
    '181203': 5},
   'age': 19,
   'case_id': 20140101141449,
   'hours_worked_per_week': 25,
   'sex': 2,
   'weight': 10005764.170853},
  {'activities': {'010101': 520,
    '010201': 50,
    '020201': 20,
    '050101': 750,
    '110101': 40,
    '160101': 60},
   'age': 38,
   'case_id': 20140101141488,
   'hours_worked_per_week': 60,
   'sex': 2,
   'weight': 3182441.982771},
  {'activities': {'010101': 390,
    '010201': 50,
    '020201': 5,
    '020701': 120,
    '050101': 260,
    '110101': 85,
    '120301': 240,
    '120303': 230,
    '180501': 60},
   'age': 75,
   'case_id': 20140101141502,
   'hours_worked_per_week': 18,
   'sex': 1,
   'weight': 15517830.495581},
  {'activities': {'010101': 700,
    '020601': 30,
    '020602': 60,
    '050101': 240,
    '110101': 125,
    '120303': 90,
    '120312': 30,
    '180206': 60,
    '189999': 30,
    '500103': 45,
    '500107': 30},
   'age': 54,
   'case_id': 20140101141515,
   'hours_worked_per_week': 50,
   'sex': 2,
   'weight': 2716263.447172},
  {'activities': {'010101': 510,
    '020401': 120,
    '020701': 60,
    '070102': 15,
    '110101': 75,
    '120303': 575,
    '180702': 10,
    '181101': 45,
    '181205': 30},
   'age': 49,
   'case_id': 20140101141556,
   'hours_worked_per_week': 45,
   'sex': 1,
   'weight': 5168270.982215},
  {'activities': {'010101': 375,
    '010201': 75,
    '020201': 40,
    '020203': 105,
    '030101': 15,
    '030112': 21,
    '070103': 15,
    '070104': 10,
    '110101': 42,
    '120101': 30,
    '120303': 90,
    '120307': 15,
    '120308': 105,
    '150101': 100,
    '160102': 45,
    '180301': 79,
    '180703': 18,
    '180704': 25,
    '189999': 15,
    '500101': 220},
   'age': 51,
   'case_id': 20140101141584,
   'hours_worked_per_week': -1,
   'sex': 2,
   'weight': 8381281.655505},
  {'activities': {'010101': 600,
    '010201': 30,
    '020101': 45,
    '020201': 35,
    '020203': 15,
    '020601': 90,
    '020904': 15,
    '070104': 10,
    '080501': 90,
    '110101': 53,
    '120101': 105,
    '120303': 90,
    '120308': 45,
    '120403': 153,
    '180704': 20,
    '180805': 20,
    '181101': 2,
    '181204': 22},
   'age': 80,
   'case_id': 20140101141589,
   'hours_worked_per_week': -1,
   'sex': 2,
   'weight': 13118333.276316},
  {'activities': {'010101': 420,
    '010201': 90,
    '050401': 120,
    '050403': 25,
    '050499': 5,
    '120303': 705,
    '180504': 75},
   'age': 52,
   'case_id': 20140101141629,
   'hours_worked_per_week': -1,
   'sex': 2,
   'weight': 13575415.134816},
  {'activities': {'010101': 470,
    '010201': 40,
    '020201': 40,
    '020202': 15,
    '020203': 15,
    '030101': 120,
    '030102': 45,
    '030103': 60,
    '030112': 5,
    '050101': 220,
    '070104': 10,
    '110101': 45,

### If you wish to query by activity, then use the activity number.
#### You can use the numbers in three different ways:
* to refer to the activity category: 'Personal Care' ../activity/01/
* to refer to the activity sub-category: 'Sleeping' ../activity/0101/
* to refer to a specific activity: 'Sleeplessness' ../activity/010102/

######Activity Category:

In [4]:
all_actcode = requests.get('https://autus-project.herokuapp.com/activity/01/')
all_actcode.json()

{'average_minutes': 64.46545510313626,
 'code': '01',
 'codes': ['01'],
 'total_number_of_respondents_calculated': 104328}

######Activity Sub-category:

In [5]:
second_actcode = requests.get('https://autus-project.herokuapp.com/activity/0101/')
second_actcode.json()

{'average_minutes': 266.76000690131127,
 'code': '0101',
 'codes': ['01', '01'],
 'total_number_of_respondents_calculated': 23184}

######Specific Category:

In [6]:
third_activity_code = requests.get('https://autus-project.herokuapp.com/activity/010102/')
third_activity_code.json()

{'average_minutes': 4.146652864044168,
 'code': '010102',
 'codes': ['01', '01', '02'],
 'total_number_of_respondents_calculated': 11592}

### Using the same syntax from above, you can filter through specific activities and activity categories.
#### This filter uses pagination, with an initial offset equal to 0. 
* Change the offset by increments of 100 to maintain continuity of the results.

######Some Examples:

In [7]:
activity = requests.get('https://autus-project.herokuapp.com/activities/01/?age_gt=20&offset=200')
activity.json()

{'activities': {'average_minutes': 65.49777777777778,
  'code': '01',
  'codes': ['01'],
  'total_number_of_respondents_calculated': 100},
 'filt': {'age_gt': '20', 'offset': '200'}}

##### Feel free increment the offset by however much you'd like:

In [8]:
activity_2 = requests.get('https://autus-project.herokuapp.com/activities/01/?sex=2&offset=42')
activity_2.json()

{'activities': {'average_minutes': 67.34,
  'code': '01',
  'codes': ['01'],
  'total_number_of_respondents_calculated': 100},
 'filt': {'offset': '42', 'sex': '2'}}

In [9]:
activity_3 = requests.get('https://autus-project.herokuapp.com/activities/01/?hours_worked_per_week_lte=40')
activity_3.json()

{'activities': {'average_minutes': 64.83666666666667,
  'code': '01',
  'codes': ['01'],
  'total_number_of_respondents_calculated': 100},
 'filt': {'hours_worked_per_week_lte': '40'}}

By Bekk Blando and Soren Olegnowicz